### ISSUE TITLE
Is this the original or modified WaveGlow?

### ISSUE THREAD

**Issue by ghost** [LEEYOONHYUNG/BVAE-TTS#5]
Hello, 
Thank you for this repo. 
[config.txt](https://github.com/LEEYOONHYUNG/BVAE-TTS/files/5975239/config.txt)

I trained a model using the subdirectory "WaveGlow" in your project, however, the resulting model size (checkpoint) is 1.28 GB (1,379,402,815 bytes) which does not equal the size of the file waveglow_256channels.pt which is 644 MB (675,869,623 bytes)

What am I doing wrong?

**Comment by LEEYOONHYUNG** [comment]
I think the checkpoint is provided in fp16 precision, instead of fp32.

I provided the checkpoint and WaveGlow folder because when I generated samples for the ICLR paper, I used the WaveGlow that I had downloaded last year, but the original WaveGlow repo has been updated.

Therefore, I recommend you to use the WaveGlow provided in this repo only for generating samples and not for training.
If you want to train your own WaveGlow, please refer the original WaveGlow repo.

**Comment by ghost** [comment]
Thank you so much for your detailed response.
I am using my own corpus, so I have to train a WavGlow version that is compatible with your repository. I will train using the provided version and let you know if it works.

**Comment by ghost** [comment]
I used your WavGlow version, the resulting model size (checkpoint) is still 1.28 GB (1,379,402,815 bytes).
